{% set name = "proteus" %}
{% set version = "1.3.1" %}
{% set sha256 = "9695e9fea25064588fee0909320a67dcfec8ea7dcb89b88345a08bf1aff22e38" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/erdc-cm/proteus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - cmake
    - python
    - libgcc
    - gcc
    - git
    - libgfortran
    - openssl
    - bzip2
    - sqlite
    - openblas
    - gawk
  run:
    - python
    - jupyter
    - libgfortran
    - libgcc
    - openblas

about:
  home: https://github.com/erdc-cm/proteus
  license: NASA OPEN SOURCE AGREEMENT VERSION 1.3
  license_family: Other
  license_file: LICENSE.txt
  summary: A computational methods and simulation toolkit.
  doc_url: http://proteustoolkit.org/
  dev_url: https://github.com/mathiasertl/fabric
